// ===== CONFIG (REPLACE WITH YOUR ACTUAL KEYS) =====
const SUPABASE_URL = 'https://xxpfocgthwrtfawsbdlp.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4cGZvY2d0aHdydGZhd3NiZGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMTk1ODAsImV4cCI6MjA5MDY5NTU4MH0.gXfLsbaxmn0ZLCKM1g6uJscKGyOuVkFy_fRK1tuWAiY';
