// ===== CONFIG (REPLACE WITH YOUR ACTUAL KEYS) =====
const SUPABASE_URL = 'https://dlckscxlyxpxrvuryvnh.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsY2tzY3hseXhweHJ2dXJ5dm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwOTMzMDMsImV4cCI6MjA5MDY2OTMwM30.Waq3yVWWQpICZOU_T7j4maxlTeILB-qRmFZN6Z6L1F4';
